name: Get GCP VM Info

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Triggers the workflow on pushes to the 'main' branch (can be changed)

jobs:
  get_vm_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to write files to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Can be changed to another version if needed

      - name: Install Google Cloud SDK and Python dependencies
        run: |
          pip install google-cloud-compute

      - name: Authenticate to GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA }}
        run: |
          echo "$GCP_SA_KEY" > gcp_service_account.json
          export GOOGLE_APPLICATION_CREDENTIALS=gcp_service_account.json

      - name: Run Python script to get VM data
        id: run_script
        run: python get_gcp_vm_info.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'gcp_vm_info.json' # The file created by the script
          message: 'Update GCP VM information'
          committer_name: 'GitHub Actions'
          committer_email: 'actions@github.com'
          # branch: 'main' # Uncomment and set if pushing to a specific branch is desired
          # force: true # Use with caution, as it can overwrite existing files
